### ISSUE TITLE
MDClub 附带的.nginx.conf 文件问题

### ISSUE THREAD

**Issue by actual123321** [zdhxiong/mdclub#10]
如图所示，我在站点Nginx配置文件里面修改了默认端口，但是发现网站加载js文件时会在域名后面添加我设置的端口，然后无法访问，删掉端口可以进行访问，排查了一下感觉是MDClub 附带的.nginx.conf和我的站点文件有冲突，请问这个有什么解决办法吗？
![1](https://user-images.githubusercontent.com/72133522/97804874-81e27300-1c8d-11eb-8f35-5b7a1157edb1.png)
![2](https://user-images.githubusercontent.com/72133522/97804879-84dd6380-1c8d-11eb-83a2-57ee05c431d4.png)
![3](https://user-images.githubusercontent.com/72133522/97804880-84dd6380-1c8d-11eb-88bd-dc78f32a3840.png)
![4](https://user-images.githubusercontent.com/72133522/97804881-8575fa00-1c8d-11eb-80b8-01c8201d20c7.png)

**Comment by zdhxiong** [comment]
说明你没改对，监听的仍然是80端口
