### ISSUE TITLE
作者大大  是否可以加入主题点赞功能？

### ISSUE THREAD

**Issue by Yakumo-Yukari** [zdhxiong/mdclub#11]
![20201109175029](https://user-images.githubusercontent.com/12076232/98525908-182d1f00-22b4-11eb-82a3-388dcde8d464.png)

别人 用户觉得这个文章或者问答不错可以给帖子或者文章点赞 在帖子底部列出点赞用户的头像呢？

比如像图片上这种

**Comment by zdhxiong** [comment]
接口有的，你可以自己开发
