### ISSUE TITLE
有没有开发计划？

### ISSUE THREAD

**Issue by nkeonkeo** [zdhxiong/mdclub#3]
比如站内搜索，站内找人

**Comment by zhoujin7** [comment]
同问+1

**Comment by lodisy** [comment]
建议完善插件开发文档，只集成基本核心功能，附加的功能可以独立出来作为组件，由社区第三方开发

**Comment by MUKAPP** [comment]
> 建议完善插件开发文档，只集成基本核心功能，附加的功能可以独立出来作为插件，由官方和社区第三方共同开发

插件可以有！
