### ISSUE TITLE
源代码格式化问题

### ISSUE THREAD

**Issue by zxcvbnm3057** [zdhxiong/mdclub#31]
请问作者源码中每个方法和类的头注释都是手动输入的吗，还有`public\static\openapi.yaml`的openapi文档是如何生成的

**Comment by zdhxiong** [comment]
注释都是手写的。
openapi 文档在另一个项目中维护（[mdclub-openapi](https://github.com/zdhxiong/mdclub-openapi)），也是手写的。

**Comment by zxcvbnm3057** [comment]
厉害。。。我想在这个项目上二次开发，刚看了个大概，感谢作者写的详细注释，不过抽象层这么多真的有必要吗

**Comment by zxcvbnm3057** [comment]
我用的vscode，保存自动格式化会导致很多git变更不利于review，请问您格式化程序配置是什么呢

**Comment by zdhxiong** [comment]
代码格式化使用的 phpcs，项目中已经内置了 phpcs 及配置文件，在 vscode 中安装 phpcs 插件即可。

**Comment by zxcvbnm3057** [comment]
好的谢谢

**Comment by zxcvbnm3057** [comment]
在development环境下能否使用vscode配合edge调试`mdclub-theme-material`项目呢，安装了`Debugger for Microsoft Edge`插件并且attach到edge进程上，但是代码断点行号错误，无法命中

**Comment by zdhxiong** [comment]
可能没有正确生成 sourcemap 文件，你先自己搜索看能否解决

**Comment by zxcvbnm3057** [comment]
文件映射没问题，执行`npm run-script dev`时不知道什么命令把js文件重新格式化了，导致两边文件行对应不上。问题是看了好几遍config文件了也没找到是谁格式化的

**Comment by zxcvbnm3057** [comment]
找到问题了，`webpack.common.js`中用于ES5转换器`buble-loader`的锅，用`babel-loader`就好了
