### ISSUE TITLE
官方社区无法发送注册验证邮件！

### ISSUE THREAD

**Issue by xmosnewone** [zdhxiong/mdclub#41]
请问社区管理员是否想临时关闭了论坛的注册功能？想回复其他朋友的帖子的都注册不了！另外，本地测试安装的时候发现一个小问题,mc_user表的email 字段长度是320，会导致安装时候报错！应该改成32就可以了，错误原因是索引长度值过长了！

**Comment by zdhxiong** [comment]
不开放注册了。
报错是你的 mysql 版本太低了，5.7.7 以上才支持更长的索引长度。
