### ISSUE TITLE
mdclub后端的go语言版本

### ISSUE THREAD

**Issue by 1379** [zdhxiong/mdclub#5]
[mdclub-go](https://github.com/1379/mdclub-go)
上面是我在业余时间用来学习go的一个项目，打算复刻一下mdclub的后端。
目前已经实现了基本的框架和几个接口，且框架分层明确，代码简洁，易于扩展。

我将会持续开发，欢迎大家一起贡献力量~

另外，由于我本人对于前端不是很懂，想请教一下作者关于mdclub前端的问题，issue不便探讨，作者能否告知一下邮箱

**Comment by zdhxiong** [comment]
@1379 我的 github 主页有邮箱
