### ISSUE TITLE
SodionAuth联动需求

### ISSUE THREAD

**Issue by hs-err** [zdhxiong/mdclub#6]
https://github.com/Mohist-Community/SodionAuth

如果在插件内添加SodionAuth，我注意到你的api文档中提供的登录方法需要验证码的验证，是否可以像xenforo提供一个需要管理员token的无限制的验证密码api。

如果在网站上添加SodionAuthApi，可以参考 https://github.com/Mohist-Community/SodionAuthFlarum https://github.com/Mohist-Community/SodionAuthPhp 实现。

如果使用添加api方式，请回复是否需要pull request
（很棒的项目，我会在熟悉结构后参与开发

**Comment by zdhxiong** [comment]
验证码是为了防止暴力破解。
正常情况下是不需要输入验证码的。只有连续多次输错了密码，才要求输入验证码。
加一个可以无限验证的 api 反而增加了被暴破的可能。

**Comment by hs-err** [comment]
> 验证码是为了防止暴力破解。
> 正常情况下是不需要输入验证码的。只有连续多次输错了密码，才要求输入验证码。
> 加一个可以无限验证的 api 反而增加了被暴破的可能。

如果将无限验证的api要求管理员的token是否可以解决这一问题?

**Comment by zdhxiong** [comment]
> 如果将无限验证的api要求管理员的token是否可以解决这一问题?
不行。
不想用户输验证码的话，可以提示用户24小时后再试，24小时后就可以不输验证码再次登录。
这是正常的逻辑，如果可以无限验证，很容易就能把密码破解。

**Comment by hs-err** [comment]
> > 如果将无限验证的api要求管理员的token是否可以解决这一问题?
> > 不行。
> > 不想用户输验证码的话，可以提示用户24小时后再试，24小时后就可以不输验证码再次登录。
> > 这是正常的逻辑，如果可以无限验证，很容易就能把密码破解。

这个API不是提供给用户使用的，是提供给其他的程序，另一个使用mdclub用户信息的程序

**Comment by zdhxiong** [comment]
你自己去开发吧。不要提交pr。
